// /src/components/campaigns/mockData.ts
import { Campaign } from "./types";

// Mock data para las campañas
export const mockCampaigns: Campaign[] = [
  {
    id: "23810",
    name: "LiveNation_Brasil_Bad Bunny_Vevo_MaioJunho25",
    organizationType: "Advertiser",
    startDate: "2025-05-13",
    endDate: "2025-06-11",
    status: "Approved",
    units: 150000,
    budget: 75000,
    grossMargin: 28.5,
    salesperson: "Luciana Egurrola",
    trafficker: "Octavio Martínez",
    customer: "Live Nation",
    notes: "Cliente requiere informes semanales de rendimiento",
    internalNotes: "Prioridad alta - cliente estratégico",
    billingParty: "Live Nation Brasil Entretenimento LTDA",
    billingOffice: "Miami",
    accountManager: "Octavio Martinez",
    adOpsLeader: "Ana Sobreyra",
    industry: "Entertainment",
    adUnits: [
      {
        id: "0001",
        line: "1",
        publisher: "Vevo",
        market: "Brazil",
        channel: "Cross Platform Takeover VIDEO",
        format: "Display",
        size: "Takeover",
        units: 100000,
        model: "CPM",
        margin: "28.5%",
        unitCost: 0.5,
        usmcRate: 0.38,
        clientNetRate: 0.5,
        investment: 50000,
        startDate: "2025-05-13",
        endDate: "2025-05-31",
        status: "Approved",
      },
      {
        id: "0002",
        line: "2",
        publisher: "Vevo",
        market: "Brazil",
        channel: "Cross Platform Takeover VIDEO",
        format: "Display",
        size: "Takeover",
        units: 50000,
        model: "CPM",
        margin: "28.5%",
        unitCost: 0.5,
        usmcRate: 0.42,
        clientNetRate: 0.5,
        investment: 25000,
        startDate: "2025-06-01",
        endDate: "2025-06-11",
        status: "Pending",
      },
    ],
  },
  {
    id: "23809",
    name: "Alpura_Deslactosada_Podcast ads_Mex_Jun25",
    organizationType: "Agencia",
    startDate: "2025-06-01",
    endDate: "2025-06-30",
    status: "Live",
    units: 85000,
    budget: 32000,
    grossMargin: 22.7,
    salesperson: "Ana Sobreyra",
    trafficker: "Octavio Martínez",
    customer: "Alpura",
    notes: "",
    internalNotes: "Nuevo cliente, trato preferencial",
    billingParty: "Havas Media Mexico City",
    billingOffice: "Mexico",
    accountManager: "Ana Sobreyra",
    adOpsLeader: "N/A",
    industry: "Food & Beverage",
    adUnits: [
      {
        id: "0001",
        line: "1",
        publisher: "Spotify",
        market: "Mexico",
        channel: "Podcast Audio Ads",
        format: "Audio",
        size: "30s",
        units: 85000,
        model: "CPM",
        margin: "22.7%",
        unitCost: 0.38,
        usmcRate: 0.3,
        clientNetRate: 0.38,
        investment: 32000,
        startDate: "2025-06-01",
        endDate: "2025-06-30",
        status: "Live",
      },
    ],
  },
  {
    id: "23796",
    name: "FANDOM | MAX (ARG) | FINAL | Mayo 25",
    organizationType: "Publisher",
    startDate: "2025-05-19",
    endDate: "2025-06-25",
    status: "Implementation",
    units: 110000,
    budget: 52000,
    grossMargin: 29.6,
    salesperson: "Luciana Egurrola",
    trafficker: "Octavio Martínez",
    customer: "MAX",
    notes: "Solicitud de informes diarios de performance",
    internalNotes: "Implementación crítica - cliente exigente",
    billingParty: "Fandom Inc.",
    billingOffice: "Miami",
    accountManager: "Octavio Martinez",
    adOpsLeader: "Ana Sobreyra",
    industry: "Media",
    adUnits: [
      {
        id: "0001",
        line: "1",
        publisher: "Fandom",
        market: "Argentina",
        channel: "Cross Platform Takeover VIDEO",
        format: "Display",
        size: "Takeover",
        units: 60000,
        model: "CPM",
        margin: "29.6%",
        unitCost: 0.45,
        usmcRate: 0.35,
        clientNetRate: 0.45,
        investment: 27000,
        startDate: "2025-05-19",
        endDate: "2025-05-31",
        status: "Implementation",
      },
      {
        id: "0002",
        line: "2",
        publisher: "Fandom",
        market: "Argentina",
        channel: "Cross Platform Takeover VIDEO",
        format: "Display",
        size: "Takeover",
        units: 50000,
        model: "CPM",
        margin: "29.6%",
        unitCost: 0.5,
        usmcRate: 0.4,
        clientNetRate: 0.5,
        investment: 25000,
        startDate: "2025-06-01",
        endDate: "2025-06-25",
        status: "Pending",
      },
    ],
  },
];

// Obtener campaña por ID
export const getMockCampaignById = (id: string): Campaign | undefined => {
  return mockCampaigns.find((campaign) => campaign.id === id);
};
