// /src/components/campaigns/mockData.ts
import { Campaign, AdUnit } from "./types";

// Mock data para las campañas
export const mockCampaigns: Campaign[] = [
  {
    id: "22043",
    name:
      "Banorte_Banorte_Hotsale _Credito Pyme _Linkedin_Mex_Junio25_Linkedin_Jun_Mexico",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-01",
    endDate: "2025-06-30",
    status: "Approved",
    units: 500000,
    budget: 150000,
    grossMargin: 15,
    salesperson: "Gabriela Hurtado",
    trafficker: "Ana Sobreyra",
    customer: "Banorte",
    advertiser: "Banorte",
    billingParty: "Havas Meadia CV de SAPI",
    billingOffice: "Mexico",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Bank",
    organizationPublisher: "Linkedin",
    customerBillingParty: "Havas Media-Mexico",
    agencyContact: "Alondra Vargas",
    billingContact: "Maria Gutierrez",
    cioOwner: "USMC",
    targetMarket: "Mexico",
    notes:
      "Campaña para promocionar créditos Pyme de Banorte durante el HotSale de junio 2025",
    internalNotes:
      "Cliente prioritario, requiere atención especial y reportes semanales",
    adUnits: [
      {
        id: "au-1",
        line: "1",
        publisher: "Linkedin",
        market: "Mexico",
        channel: "ROS",
        format: "Display",
        size: "300x250",
        units: 300000,
        model: "CPM",
        margin: "15%",
        unitCost: 12,
        customerInvestment: 6750,
        customerNetRate: 33.12,
        startDate: "2025-06-01",
        endDate: "2025-06-15",
        status: "Approved",
        agencyCommission: 10,
        localTaxes: 16,
        grossMargin: 32,
        publisherNetCost: 6075,
        publisherOpenRate: 22.5,
        publisherCommission: 5,
      },
      {
        id: "au-2",
        line: "2",
        publisher: "Linkedin",
        market: "Mexico",
        channel: "Home Page",
        format: "Display",
        size: "300x250",
        units: 200000,
        model: "CPM",
        margin: "18%",
        unitCost: 25,
        customerInvestment: 2500,
        customerNetRate: 18.38,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Approved",
        agencyCommission: 12,
        localTaxes: 16,
        grossMargin: 32,
        publisherNetCost: 2250,
        publisherOpenRate: 12.5,
        publisherCommission: 4,
      },
    ],
  },
  {
    id: "22044",
    name:
      "Nintendo_Nintendo_Display Digital_Wetransfer_Static_Bra_Mex_Chi_Col_Per_May_Jun_25_Wetransfer_Jun_Brazil,Chile,Colombia,Mexico,Peru",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-02",
    endDate: "2025-06-28",
    status: "Implementation",
    units: 750000,
    budget: 225000,
    grossMargin: 18,
    salesperson: "Felipe Alvarez",
    trafficker: "Bruno Tellez",
    customer: "Nintendo",
    advertiser: "Nintendo",
    billingParty: "Miami",
    billingOffice: "Miami",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Gaming",
    organizationPublisher: "Fandom",
    customerBillingParty: "Omnet-United States-OMG",
    agencyContact: "Carlos Eljaeik",
    billingContact: "Gonzalo Pazos",
    cioOwner: "USMC",
    targetMarket: "Brasil, Mexico, Chile,Colombia, Peru",
    notes:
      "Campaña multinacional para promocionar nuevos lanzamientos de Nintendo",
    internalNotes:
      "Cliente con presencia en múltiples mercados latinoamericanos",
    adUnits: [
      {
        id: "au-3",
        line: "1",
        publisher: "Fandom",
        market: "Brazil",
        channel: "ROS",
        format: "Display",
        size: "728x90",
        units: 250000,
        model: "CPM",
        margin: "18%",
        unitCost: 14,
        customerInvestment: 11552.5,
        customerNetRate: 103.15,
        startDate: "2025-06-02",
        endDate: "2025-06-15",
        status: "Implementation",
        agencyCommission: 12,
        localTaxes: 14,
        grossMargin: 55,
        publisherNetCost: 10166.2,
        publisherOpenRate: 46.21,
        publisherCommission: 6,
      },
      {
        id: "au-4",
        line: "2",
        publisher: "WeTransfer",
        market: "Mexico",
        channel: "Display",
        format: "Display",
        size: "Banner",
        units: 300000,
        model: "CPM",
        margin: "20%",
        unitCost: 16,
        customerInvestment: 4800,
        customerNetRate: 24,
        startDate: "2025-06-10",
        endDate: "2025-06-28",
        status: "Implementation",
        agencyCommission: 14,
        localTaxes: 16,
        grossMargin: 25,
        publisherNetCost: 4128,
        publisherOpenRate: 15,
        publisherCommission: 4,
      },
      {
        id: "au-5",
        line: "3",
        publisher: "WeTransfer",
        market: "Colombia",
        channel: "Display",
        format: "Display",
        size: "Interstitial",
        units: 200000,
        model: "CPM",
        margin: "16%",
        unitCost: 12,
        customerInvestment: 2400,
        customerNetRate: 18,
        startDate: "2025-06-15",
        endDate: "2025-06-28",
        status: "Implementation",
        agencyCommission: 10,
        localTaxes: 15,
        grossMargin: 20,
        publisherNetCost: 2160,
        publisherOpenRate: 11,
        publisherCommission: 4,
      },
    ],
  },
  {
    id: "22045",
    name: "Paramount+_De Férias Com o Ex__Jun_Brazil",
    campaignType: "Programmatic",
    organizationType: "Direct",
    startDate: "2025-06-03",
    endDate: "2025-06-25",
    status: "Won",
    units: 350000,
    budget: 80000,
    grossMargin: 22,
    salesperson: "Laura Ponso",
    trafficker: "Bruno Tellez",
    customer: "Paramount",
    advertiser: "Paramount",
    billingParty: "Brazil",
    billingOffice: "Brazil",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Streaming",
    organizationPublisher: "Tinder",
    customerBillingParty: "Paramount",
    agencyContact: "Angelica Bito",
    billingContact: "Carla Rodriguez",
    cioOwner: "Customer",
    targetMarket: "Brazil",
    notes:
      "Campaña para promocionar el reality show 'De Férias Com o Ex' en Paramount+",
    internalNotes: "Cliente directo, sin agencia intermediaria",
    adUnits: [
      {
        id: "au-6",
        line: "1",
        publisher: "Tinder",
        market: "Brazil",
        channel: "ROA - Run Of App",
        format: "Display",
        size: "Native Display Card",
        units: 200000,
        model: "CPM",
        margin: "22%",
        unitCost: 0.8,
        customerInvestment: 1500,
        customerNetRate: 13.39,
        startDate: "2025-06-03",
        endDate: "2025-06-15",
        status: "Won",
        agencyCommission: 0,
        localTaxes: 12,
        grossMargin: 44,
        publisherNetCost: 1320,
        publisherOpenRate: 7.5,
        publisherCommission: 0,
      },
      {
        id: "au-7",
        line: "2",
        publisher: "Tinder",
        market: "Brazil",
        channel: "ROA - Run Of App",
        format: "Video",
        size: "Native Video Card",
        units: 150000,
        model: "CPM",
        margin: "25%",
        unitCost: 18,
        customerInvestment: 1125,
        customerNetRate: 13.39,
        startDate: "2025-06-15",
        endDate: "2025-06-25",
        status: "Won",
        agencyCommission: 0,
        localTaxes: 12,
        grossMargin: 44,
        publisherNetCost: 990,
        publisherOpenRate: 7.5,
        publisherCommission: 0,
      },
    ],
  },
  {
    id: "22046",
    name: "Pernod Ricard_Buhero Negro - PG_OneFootball_Jun_Argentina",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-04",
    endDate: "2025-06-30",
    status: "Materials & Creatives OK",
    units: 420000,
    budget: 95000,
    grossMargin: 20,
    salesperson: "Alvaro Vera",
    trafficker: "Bruno Tellez",
    customer: "Pernord Ricard",
    advertiser: "Pernord Ricard",
    billingParty: "Miami",
    billingOffice: "Miami",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Food and Beverage",
    organizationPublisher: "OneFootball",
    customerBillingParty: "Carat-Argentina",
    agencyContact: "Matias Ramirez",
    billingContact: "Paulina Rubio",
    cioOwner: "Customer",
    targetMarket: "Argentina",
    notes:
      "Campaña para promocionar bebidas de Pernod Ricard en Argentina durante eventos deportivos",
    internalNotes: "Cliente solicita reports diarios de performance",
    adUnits: [
      {
        id: "au-8",
        line: "1",
        publisher: "OneFootball",
        market: "Argentina",
        channel: "Low Display (Tier 1 Display)",
        format: "Display",
        size: "320x50",
        units: 250000,
        model: "CPM",
        margin: "20%",
        unitCost: 10,
        customerInvestment: 290,
        customerNetRate: 2.07,
        startDate: "2025-06-04",
        endDate: "2025-06-20",
        status: "Materials & Creatives OK",
        agencyCommission: 12,
        localTaxes: 21,
        grossMargin: 44,
        publisherNetCost: 255.2,
        publisherOpenRate: 1.16,
        publisherCommission: 3,
      },
      {
        id: "au-9",
        line: "2",
        publisher: "OneFootball",
        market: "Argentina",
        channel: "Video",
        format: "Video",
        size: "PRE-ROLL - SKIPPABLE (12 - 30 SEC)",
        units: 170000,
        model: "CPM",
        margin: "22%",
        unitCost: 22,
        customerInvestment: 4250,
        customerNetRate: 44.64,
        startDate: "2025-06-10",
        endDate: "2025-06-30",
        status: "Materials & Creatives OK",
        agencyCommission: 12,
        localTaxes: 21,
        grossMargin: 44,
        publisherNetCost: 3740,
        publisherOpenRate: 25.0,
        publisherCommission: 3,
      },
    ],
  },
  {
    id: "22047",
    name: "PUIG_PUIG BANDERAS_Wetransfer_Jun_Mexico",
    campaignType: "Programmatic",
    organizationType: "Agency",
    startDate: "2025-06-05",
    endDate: "2025-06-30",
    status: "Pending",
    units: 380000,
    budget: 110000,
    grossMargin: 17,
    salesperson: "Diego Rivera",
    trafficker: "Bruno Tellez",
    customer: "PUIG",
    advertiser: "PUIG",
    billingParty: "Méxicp",
    billingOffice: "Méxicp",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Beauty",
    organizationPublisher: "WeTransfer",
    customerBillingParty: "Starcom-Mexico",
    agencyContact: "Edy Reyes",
    billingContact: "Charly Garcia",
    cioOwner: "Customer",
    targetMarket: "México",
    notes:
      "Campaña para promocionar la nueva línea de fragancias BANDERAS de PUIG",
    internalNotes:
      "Campaña con materiales pendientes por aprobar por el cliente",
    adUnits: [
      {
        id: "au-10",
        line: "1",
        publisher: "WeTransfer",
        market: "Mexico",
        channel: "Display",
        format: "Display",
        size: "Banner",
        units: 200000,
        model: "CPM",
        margin: "17%",
        unitCost: 15,
        customerInvestment: 3000,
        customerNetRate: 22,
        startDate: "2025-06-05",
        endDate: "2025-06-20",
        status: "Pending",
        agencyCommission: 11,
        localTaxes: 16,
        grossMargin: 20,
        publisherNetCost: 2670,
        publisherOpenRate: 14,
        publisherCommission: 4,
      },
      {
        id: "au-11",
        line: "2",
        publisher: "WeTransfer",
        market: "Mexico",
        channel: "Display",
        format: "Display",
        size: "Takeover",
        units: 180000,
        model: "CPM",
        margin: "19%",
        unitCost: 25,
        customerInvestment: 4500,
        customerNetRate: 36,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Pending",
        agencyCommission: 11,
        localTaxes: 16,
        grossMargin: 22,
        publisherNetCost: 4005,
        publisherOpenRate: 23,
        publisherCommission: 4,
      },
    ],
  },
  {
    id: "22048",
    name: "Red Hat_Connected Campaign_TikTok_Jun_Latam",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-06",
    endDate: "2025-06-30",
    status: "Negotiating",
    units: 600000,
    budget: 180000,
    grossMargin: 20,
    salesperson: "Franco Bontempi",
    trafficker: "Bruno Tellez",
    customer: "Red Hat",
    advertiser: "Red Hat",
    billingParty: "Argentina",
    billingOffice: "Argentina",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Technology",
    organizationPublisher: "TikTok",
    customerBillingParty: "OMD- Argentina",
    agencyContact: "Micaela Molto",
    billingContact: "Gustavo Cerati",
    cioOwner: "USMC",
    targetMarket: "Chile,Colombia, Peru",
    notes:
      "Campaña regional para promocionar soluciones de conectividad de Red Hat",
    internalNotes:
      "Negociación en curso con TikTok para obtener descuentos adicionales",
    adUnits: [
      {
        id: "au-12",
        line: "1",
        publisher: "TikTok",
        market: "Chile",
        channel: "RON",
        format: "Video",
        size: "In Feed",
        units: 250000,
        model: "CPV",
        margin: "20%",
        unitCost: 0.15,
        customerInvestment: 37500,
        customerNetRate: 0.23,
        startDate: "2025-06-06",
        endDate: "2025-06-20",
        status: "Negotiating",
        agencyCommission: 15,
        localTaxes: 19,
        grossMargin: 22,
        publisherNetCost: 31875,
        publisherOpenRate: 0.14,
        publisherCommission: 5,
      },
      {
        id: "au-13",
        line: "2",
        publisher: "TikTok",
        market: "Peru",
        channel: "RON",
        format: "Video",
        size: "In Feed",
        units: 200000,
        model: "CPV",
        margin: "20%",
        unitCost: 0.14,
        customerInvestment: 28000,
        customerNetRate: 0.22,
        startDate: "2025-06-06",
        endDate: "2025-06-30",
        status: "Negotiating",
        agencyCommission: 15,
        localTaxes: 18,
        grossMargin: 22,
        publisherNetCost: 23800,
        publisherOpenRate: 0.13,
        publisherCommission: 5,
      },
      {
        id: "au-14",
        line: "3",
        publisher: "TikTok",
        market: "Colombia",
        channel: "RON",
        format: "Video",
        size: "Collection Ads",
        units: 150000,
        model: "CPV",
        margin: "20%",
        unitCost: 0.13,
        customerInvestment: 19500,
        customerNetRate: 0.21,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Negotiating",
        agencyCommission: 15,
        localTaxes: 19,
        grossMargin: 22,
        publisherNetCost: 16575,
        publisherOpenRate: 0.12,
        publisherCommission: 5,
      },
    ],
  },
  {
    id: "22049",
    name: "Yakult_Campana anual_WeTransfer_Jun_Mexico",
    campaignType: "Programmatic",
    organizationType: "Direct",
    startDate: "2025-06-07",
    endDate: "2025-06-30",
    status: "Pending",
    units: 300000,
    budget: 90000,
    grossMargin: 25,
    salesperson: "Diego Rivera",
    trafficker: "Ana Sobreyra",
    customer: "Yakult",
    advertiser: "Yakult",
    billingParty: "México",
    billingOffice: "México",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Food and Beverage",
    organizationPublisher: "WeTransfer",
    customerBillingParty: "Yakult",
    agencyContact: "Erika Negrete",
    billingContact: "Humberto Rodriguez",
    cioOwner: "USMC",
    targetMarket: "México",
    notes: "Campaña anual para promocionar beneficios de Yakult para la salud",
    internalNotes: "Cliente directo con alta prioridad",
    adUnits: [
      {
        id: "au-15",
        line: "1",
        publisher: "WeTransfer",
        market: "Mexico",
        channel: "Display",
        format: "Display",
        size: "300x250",
        units: 150000,
        model: "CPM",
        margin: "25%",
        unitCost: 13,
        customerInvestment: 1950,
        customerNetRate: 22,
        startDate: "2025-06-07",
        endDate: "2025-06-20",
        status: "Pending",
        agencyCommission: 0,
        localTaxes: 16,
        grossMargin: 30,
        publisherNetCost: 1950,
        publisherOpenRate: 13,
        publisherCommission: 0,
      },
      {
        id: "au-16",
        line: "2",
        publisher: "WeTransfer",
        market: "Mexico",
        channel: "Video",
        format: "Video",
        size: "30s",
        units: 150000,
        model: "CPV",
        margin: "25%",
        unitCost: 20,
        customerInvestment: 3000,
        customerNetRate: 32,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Pending",
        agencyCommission: 0,
        localTaxes: 16,
        grossMargin: 30,
        publisherNetCost: 3000,
        publisherOpenRate: 20,
        publisherCommission: 0,
      },
    ],
  },
  {
    id: "22050",
    name: "Spotify Brazil_Fan Life - Fase 2_Vevo_Jun_Brazil",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-08",
    endDate: "2025-06-28",
    status: "Won",
    units: 450000,
    budget: 120000,
    grossMargin: 22,
    salesperson: "Gabriel Toledo",
    trafficker: "Ana Sobreyra",
    customer: "Spotify Brazil",
    advertiser: "Spotify Brazil",
    billingParty: "Brazil",
    billingOffice: "Brazil",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Music",
    organizationPublisher: "Vevo",
    customerBillingParty: "Soko",
    agencyContact: "Caio Campos",
    billingContact: "Diego Rodriguez",
    cioOwner: "USMC",
    targetMarket: "Brazil",
    notes:
      "Campaña para promocionar suscripción premium de Spotify - Fase 2 de Fan Life",
    internalNotes: "Segunda fase de campaña exitosa, prioridad alta",
    adUnits: [
      {
        id: "au-17",
        line: "1",
        publisher: "Vevo",
        market: "Brazil",
        channel: "Desktop",
        format: "Video",
        size: "15 - 30 sec skippable",
        units: 250000,
        model: "CPV",
        margin: "22%",
        unitCost: 0.18,
        customerInvestment: 45000,
        customerNetRate: 0.28,
        startDate: "2025-06-08",
        endDate: "2025-06-20",
        status: "Won",
        agencyCommission: 15,
        localTaxes: 12,
        grossMargin: 24,
        publisherNetCost: 38250,
        publisherOpenRate: 0.17,
        publisherCommission: 5,
      },
      {
        id: "au-18",
        line: "2",
        publisher: "Vevo",
        market: "Brazil",
        channel: "CTV",
        format: "Video",
        size: "short video",
        units: 200000,
        model: "CPM",
        margin: "20%",
        unitCost: 12,
        customerInvestment: 2400,
        customerNetRate: 18,
        startDate: "2025-06-15",
        endDate: "2025-06-28",
        status: "Won",
        agencyCommission: 15,
        localTaxes: 12,
        grossMargin: 22,
        publisherNetCost: 2040,
        publisherOpenRate: 11,
        publisherCommission: 5,
      },
    ],
  },
  {
    id: "22051",
    name: "Muv_Mynt_MAP_Jun",
    campaignType: "Programmatic",
    organizationType: "Agency",
    startDate: "2025-06-09",
    endDate: "2025-06-30",
    status: "Approved",
    units: 320000,
    budget: 75000,
    grossMargin: 18,
    salesperson: "Rafael Magdalena",
    trafficker: "Ana Sobreyra",
    customer: "Mynt",
    advertiser: "Mynt",
    billingParty: "Brazil",
    billingOffice: "Brazil",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Financial Technology",
    organizationPublisher: "MAP",
    customerBillingParty: "MUV-Brasil-WPP",
    agencyContact: "Carol Hévia",
    billingContact: "Flor Delgado",
    cioOwner: "Customer",
    targetMarket: "Brazil",
    notes: "Campaña para promocionar la plataforma de pagos digitales Mynt",
    internalNotes:
      "Cliente con campañas frecuentes, requiere atención detallada",
    adUnits: [
      {
        id: "au-19",
        line: "1",
        publisher: "MAP",
        market: "Brazil",
        channel: "Mobile Ad Performance",
        format: "Display",
        size: "Full Banner",
        units: 170000,
        model: "CPA",
        margin: "18%",
        unitCost: 10,
        customerInvestment: 2720,
        customerNetRate: 28.57,
        startDate: "2025-06-09",
        endDate: "2025-06-20",
        status: "Approved",
        agencyCommission: 14,
        localTaxes: 12,
        grossMargin: 44,
        publisherNetCost: 2339,
        publisherOpenRate: 16.0,
        publisherCommission: 4,
      },
      {
        id: "au-20",
        line: "2",
        publisher: "MAP",
        market: "Brazil",
        channel: "Mobile Ad Performance",
        format: "Display",
        size: "Varios",
        units: 150000,
        model: "CPA",
        margin: "20%",
        unitCost: 14,
        customerInvestment: 34.5,
        customerNetRate: 0.41,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Approved",
        agencyCommission: 14,
        localTaxes: 12,
        grossMargin: 44,
        publisherNetCost: 29.67,
        publisherOpenRate: 0.23,
        publisherCommission: 4,
      },
    ],
  },
  {
    id: "22052",
    name: "Levis_Levis Pride__Jun_Mexico",
    campaignType: "IO-based",
    organizationType: "Agency",
    startDate: "2025-06-10",
    endDate: "2025-06-30",
    status: "Materials & Creatives OK",
    units: 280000,
    budget: 65000,
    grossMargin: 20,
    salesperson: "Laura Solorzano",
    trafficker: "Ana Sobreyra",
    customer: "Levis",
    advertiser: "Levis",
    billingParty: "México",
    billingOffice: "México",
    accountManager: "Araceli Mendoza",
    adOpsLeader: "Ana Sobreyra",
    industry: "Appareil",
    organizationPublisher: "Tinder",
    customerBillingParty: "UM - Mexico - IPG",
    agencyContact: "Karen Ramirez",
    billingContact: "Ana Hurtado",
    cioOwner: "Customer",
    targetMarket: "México",
    notes: "Campaña para promocionar la colección Pride de Levis",
    internalNotes: "Materiales creativos en proceso de aprobación final",
    adUnits: [
      {
        id: "au-21",
        line: "1",
        publisher: "Tinder",
        market: "Mexico",
        channel: "ROA - Run Of App",
        format: "Display",
        size: "Branded Profile Card",
        units: 180000,
        model: "CPM",
        margin: "20%",
        unitCost: 0.75,
        customerInvestment: 2700,
        customerNetRate: 26.78,
        startDate: "2025-06-10",
        endDate: "2025-06-25",
        status: "Materials & Creatives OK",
        agencyCommission: 15,
        localTaxes: 16,
        grossMargin: 44,
        publisherNetCost: 2295,
        publisherOpenRate: 15.0,
        publisherCommission: 5,
      },
      {
        id: "au-22",
        line: "2",
        publisher: "Tinder",
        market: "Mexico",
        channel: "ROA - Run Of App",
        format: "Content Integration",
        size: "Custom Poll",
        units: 100000,
        model: "CPM",
        margin: "22%",
        unitCost: 16,
        customerInvestment: 2000,
        customerNetRate: 35.71,
        startDate: "2025-06-15",
        endDate: "2025-06-30",
        status: "Materials & Creatives OK",
        agencyCommission: 15,
        localTaxes: 16,
        grossMargin: 44,
        publisherNetCost: 1700,
        publisherOpenRate: 20.0,
        publisherCommission: 5,
      },
    ],
  },
];

// Obtener campaña por ID
export const getMockCampaignById = (id: string): Campaign | undefined => {
  return mockCampaigns.find((campaign) => campaign.id === id);
};
