import { RevenueData } from "./RevenueTable";

export const mockRevenueData: RevenueData[] = [
  {
    id: 1,
    division: "Print",
    campaignId: "23599",
    month: "April",
    year: "2025",
    account: "Universal McCann",
    partOfHolding: "Yes",
    holdingName: "IPG Mediabrands",
    advertiser: "Coca-Cola",
    product: "La Casa de los Famosos",
    publisher: "Revista 15 Minutos",
    publisherProduct: "Print",
    serviceType: "Representación Comercial",
    purchaseType: "IO-Based",
    salesPerson: "Luciana Egurrola",
    billingOffice: "Bogotá",
    billingCountry: "Colombia",
    market: "Colombia",
    currency: "USD",
    exchangeRate: "3950.25",
    fxCorporate: "3950.25",
    fxMonthlyAverage: "3920.10",
    grossRevenue: "$18,500.00",
    avb: "$550.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$14,800.00",
    hiddenCosts: "$550.00",
    netRevenue: "$3,700.00",
    margin: "20.00%",
    campaignDescription:
      "Campaña de verano para promocionar Coca-Cola Zero en el reality show La Casa de los Famosos. Incluye product placement y publicidad impresa en revista semanal.",
    internalNotes:
      "Cliente solicitó facturación en USD a pesar de ser campaña local. Requiere aprobación especial de finanzas para próximas campañas. Contacto principal: Maria Gómez (maria.gomez@coca-cola.com).",
    revenueLocal: "$72,079,625.00",
    publisherCostLocal: "$57,844,000.00",
    avbProvisionLocal: "$2,172,637.50",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: false,
  },
  {
    id: 2,
    division: "OOH",
    campaignId: "23595",
    month: "April",
    year: "2025",
    account: "H2 MARKETING S DE RL DE CV",
    partOfHolding: "No",
    holdingName: "-",
    advertiser: "Tramontina",
    product: "Acero Line",
    publisher: "Amazon Advertising",
    publisherProduct: "Amazon",
    serviceType: "Clearing House",
    purchaseType: "IO-Based",
    salesPerson: "Maria Robles",
    billingOffice: "Mexico City",
    billingCountry: "Mexico",
    market: "Mexico",
    currency: "USD",
    exchangeRate: "16.95",
    fxCorporate: "16.95",
    fxMonthlyAverage: "16.80",
    grossRevenue: "$65,000.00",
    avb: "$450.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$55,250.00",
    hiddenCosts: "$450.00",
    netRevenue: "$9,750.00",
    margin: "15.00%",
    campaignDescription:
      "Campaña digital para la línea de cocina Acero Line de Tramontina en Amazon. Enfoque en productos premium de acero inoxidable para cocineros profesionales.",
    internalNotes:
      "Campaña con descuento especial negociado por volumen anual. No aplicar descuentos adicionales sin consultar con dirección comercial.",
    revenueLocal: "$1,101,750.00",
    publisherCostLocal: "$936,487.50",
    avbProvisionLocal: "$7,627.50",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: true,
  },
  {
    id: 3,
    division: "Online",
    campaignId: "23593",
    month: "April",
    year: "2025",
    account: "Media Solutions MTY",
    partOfHolding: "Yes",
    holdingName: "Omnicom Media Group",
    advertiser: "Carl's Jr",
    product: "Thunderbolts Promo",
    publisher: "Fandom",
    publisherProduct: "Programmatic",
    serviceType: "Prefered Ad Services (PAS)",
    purchaseType: "Programmatic",
    salesPerson: "Octavio Martinez",
    billingOffice: "Mexico City",
    billingCountry: "Mexico",
    market: "Mexico",
    currency: "USD",
    exchangeRate: "16.95",
    fxCorporate: "16.95",
    fxMonthlyAverage: "16.80",
    grossRevenue: "$18,500.00",
    avb: "-",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$15,725.00",
    hiddenCosts: "-",
    netRevenue: "$2,775.00",
    margin: "15.00%",
    campaignDescription:
      "Campaña programática para promocionar la promoción Thunderbolts de Carl's Jr en sitios de gaming y entretenimiento. Target: jóvenes gamers 18-35.",
    internalNotes:
      "Cliente con historial de pagos tardíos. Verificar pago de campañas anteriores antes de aprobar nuevas inversiones. Último pago recibido con 45 días de retraso.",
    revenueLocal: "$313,575.00",
    publisherCostLocal: "$266,787.50",
    avbProvisionLocal: "-",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: false,
  },
  {
    id: 4,
    division: "Online",
    campaignId: "23589",
    month: "April",
    year: "2025",
    account: "MOSAIC MEDIA SAPI DE CV",
    partOfHolding: "Yes",
    holdingName: "Grupo Imagen",
    advertiser: "Samsung",
    product: "Galaxy S30",
    publisher: "WeTransfer",
    publisherProduct: "Fandom",
    serviceType: "Representación Comercial",
    purchaseType: "IO-Based",
    salesPerson: "Ana Sobreyra",
    billingOffice: "Mexico City",
    billingCountry: "Mexico",
    market: "Mexico",
    currency: "USD",
    exchangeRate: "16.95",
    fxCorporate: "16.95",
    fxMonthlyAverage: "16.80",
    grossRevenue: "$15,000.00",
    avb: "$750.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$12,750.00",
    hiddenCosts: "$750.00",
    netRevenue: "$2,250.00",
    margin: "15.00%",
    campaignDescription:
      "Lanzamiento del Galaxy S30 en WeTransfer. Campaña de awareness con videos creativos y banners interactivos. Enfoque en innovación tecnológica.",
    internalNotes:
      "Campaña prioritaria para Q2. Cliente estratégico con potencial de incremento de inversión para Q3 y Q4. Mantener margen mínimo de 15% en futuras negociaciones.",
    revenueLocal: "$254,250.00",
    publisherCostLocal: "$216,525.00",
    avbProvisionLocal: "$12,712.50",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: false,
  },
  {
    id: 5,
    division: "Online",
    campaignId: "23584",
    month: "April",
    year: "2025",
    account: "Mercado Libre",
    partOfHolding: "No",
    holdingName: "-",
    advertiser: "Mercado Libre",
    product: "MeliPlay",
    publisher: "Fandom",
    publisherProduct: "IMB",
    serviceType: "Servicio de Medios (IMB)",
    purchaseType: "IO-Based",
    salesPerson: "Octavio Martinez",
    billingOffice: "Mexico City",
    billingCountry: "Mexico",
    market: "Mexico",
    currency: "USD",
    exchangeRate: "16.95",
    fxCorporate: "16.95",
    fxMonthlyAverage: "16.80",
    grossRevenue: "$42,589.00",
    avb: "$250.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$34,071.20",
    hiddenCosts: "$250.00",
    netRevenue: "$8,517.80",
    margin: "20.00%",
    campaignDescription:
      "Campaña para promocionar MeliPlay, el servicio de streaming de Mercado Libre. Enfoque en contenido exclusivo y series originales latinoamericanas.",
    internalNotes:
      "Acuerdo especial de facturación: factura mensual única para todas las campañas activas. Contacto para facturación: finanzas@mercadolibre.com. Enviar reportes de performance semanalmente a equipo de marketing.",
    revenueLocal: "$722,782.55",
    publisherCostLocal: "$578,706.84",
    avbProvisionLocal: "$4,237.50",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: true,
  },
  {
    id: 6,
    division: "Broadcast",
    campaignId: "23572",
    month: "April",
    year: "2025",
    account: "MOSAIC MEDIA SAPI DE CV",
    partOfHolding: "Yes",
    holdingName: "Publicis Groupe",
    advertiser: "Penafiel",
    product: "Coco Flavor",
    publisher: "WeTransfer",
    publisherProduct: "WeTransfer",
    serviceType: "Mobile Performance",
    purchaseType: "IO-Based",
    salesPerson: "Maria Robles",
    billingOffice: "Mexico City",
    billingCountry: "Mexico",
    market: "Mexico",
    currency: "USD",
    exchangeRate: "16.95",
    fxCorporate: "16.95",
    fxMonthlyAverage: "16.80",
    grossRevenue: "$12,500.00",
    avb: "$50.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$10,625.00",
    hiddenCosts: "$50.00",
    netRevenue: "$1,875.00",
    margin: "15.00%",
    campaignDescription:
      "Campaña de performance móvil para Penafiel Coco Flavor. Enfoque en conversiones y ventas directas. Target: consumidores de bebidas refrescantes 18-45.",
    internalNotes:
      "Campaña parte de acuerdo anual con Grupo Publicis. Revisar cumplimiento de volumen comprometido para aplicar descuentos escalonados según contrato marco.",
    revenueLocal: "$212, -",
    publisherCostLocal: "$180, -",
    avbProvisionLocal: "$847.50",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: false,
  },
  {
    id: 7,
    division: "Online",
    campaignId: "23568",
    month: "April",
    year: "2025",
    account: "Warner Media",
    partOfHolding: "Yes",
    holdingName: "Warner Bros. Discovery",
    advertiser: "MAX Argentina",
    product: "The Last of Us 2",
    publisher: "Fandom",
    publisherProduct: "Fandom",
    serviceType: "Representación Comercial",
    purchaseType: "IO-Based",
    salesPerson: "Ana Sobreyra",
    billingOffice: "Buenos Aires",
    billingCountry: "Argentina",
    market: "Argentina",
    currency: "USD",
    exchangeRate: "890.50",
    fxCorporate: "890.50",
    fxMonthlyAverage: "875.00",
    grossRevenue: "$22,500.00",
    avb: "$1,750.00",
    tax: "$0.00",
    avbThirdParty: "$0.00",
    publisherCost: "$18,000.00",
    hiddenCosts: "$1,750.00",
    netRevenue: "$4,500.00",
    margin: "20.00%",
    campaignDescription:
      "Campaña para el estreno de The Last of Us 2 en MAX Argentina. Incluye contenido exclusivo, behind-the-scenes y promociones especiales para suscriptores.",
    internalNotes:
      "Campaña sujeta a regulaciones especiales de Argentina. Documentación adicional requerida para facturación internacional. Coordinación necesaria con equipo legal para próximas campañas.",
    revenueLocal: "$20,036,250.00",
    publisherCostLocal: "$16,029,000.00",
    avbProvisionLocal: "$1,558,375.00",
    taxAmountLocal: "$0.00",
    otherProvisionThirdPartyLocal: "$0.00",
    hasHUR: false,
  },
];

export const revenueMetrics = {
  grossRevenue: {
    value: "$194,589.00",
    change: "+12.5%",
    isPositive: true,
  },
  publisherCost: {
    value: "$161,221.20",
    change: "+9.8%",
    isPositive: true,
  },
  netRevenue: {
    value: "$33,367.80",
    change: "+15.2%",
    isPositive: true,
  },
  averageMargin: {
    value: "17.15%",
    change: "+2.1%",
    isPositive: true,
  },
};
