import { ReportTemplate } from "./ReportTemplates";
import { ReportColumn, ReportData } from "./ReportsTable";

// Templates de reportes
export const mockReportTemplates: ReportTemplate[] = [
  {
    id: "1",
    name: "Sales by Executive",
    description: "Report showing sales metrics by executive",
    module: "campaigns",
    isFavorite: true,
    createdAt: "2023-10-15T10:30:00Z",
    createdBy: "John Smith",
    icon: "BarChart3",
    color: "orange",
  },
  {
    id: "2",
    name: "Active Campaigns",
    description: "List of all active campaigns with key metrics",
    module: "campaigns",
    isFavorite: false,
    createdAt: "2023-09-22T14:45:00Z",
    createdBy: "Sarah Johnson",
    icon: "Activity",
    color: "blue",
  },
  {
    id: "3",
    name: "Monthly Revenue",
    description: "Monthly revenue breakdown by product and client",
    module: "finance",
    isFavorite: true,
    createdAt: "2023-11-05T09:15:00Z",
    createdBy: "Michael Brown",
    icon: "CircleDollarSign",
    color: "green",
  },
  {
    id: "4",
    name: "Campaign Performance",
    description: "Performance metrics for all campaigns",
    module: "adops",
    isFavorite: false,
    createdAt: "2023-10-10T16:20:00Z",
    createdBy: "Emily Davis",
    icon: "LineChart",
    color: "purple",
  },
  {
    id: "5",
    name: "HUR Approval Times",
    description: "Analysis of approval times for HUR requests",
    module: "hur",
    isFavorite: false,
    createdAt: "2023-11-12T11:00:00Z",
    createdBy: "David Wilson",
    icon: "FileBarChart",
    color: "amber",
  },
  {
    id: "6",
    name: "Client Acquisition",
    description: "New client acquisition report by month",
    module: "organizations",
    isFavorite: true,
    createdAt: "2023-09-30T13:45:00Z",
    createdBy: "Jennifer Lee",
    icon: "Users",
    color: "indigo",
  },
];

// Datos de ventas por ejecutivo
export const salesByExecutiveColumns: ReportColumn[] = [
  {
    id: "executive",
    name: "Executive",
    key: "executive",
    sortable: true,
    type: "text",
  },
  {
    id: "campaigns",
    name: "Campaigns",
    key: "campaigns",
    sortable: true,
    type: "number",
  },
  {
    id: "revenue",
    name: "Revenue",
    key: "revenue",
    sortable: true,
    type: "currency",
  },
  { id: "goal", name: "Goal", key: "goal", sortable: true, type: "currency" },
  {
    id: "achievement",
    name: "Achievement %",
    key: "achievement",
    sortable: true,
    type: "text",
  },
];

export const salesByExecutiveData: ReportData[] = [
  {
    executive: "John Smith",
    campaigns: 12,
    revenue: 150000,
    goal: 200000,
    achievement: "75%",
  },
  {
    executive: "Sarah Johnson",
    campaigns: 18,
    revenue: 230000,
    goal: 200000,
    achievement: "115%",
  },
  {
    executive: "Michael Brown",
    campaigns: 8,
    revenue: 120000,
    goal: 150000,
    achievement: "80%",
  },
  {
    executive: "Emily Davis",
    campaigns: 15,
    revenue: 180000,
    goal: 150000,
    achievement: "120%",
  },
  {
    executive: "David Wilson",
    campaigns: 10,
    revenue: 135000,
    goal: 175000,
    achievement: "77%",
  },
];

// Datos de campañas activas
export const activeCampaignsColumns: ReportColumn[] = [
  {
    id: "name",
    name: "Campaign Name",
    key: "name",
    sortable: true,
    type: "text",
  },
  { id: "client", name: "Client", key: "client", sortable: true, type: "text" },
  {
    id: "startDate",
    name: "Start Date",
    key: "startDate",
    sortable: true,
    type: "date",
  },
  {
    id: "endDate",
    name: "End Date",
    key: "endDate",
    sortable: true,
    type: "date",
  },
  {
    id: "budget",
    name: "Budget",
    key: "budget",
    sortable: true,
    type: "currency",
  },
  {
    id: "status",
    name: "Status",
    key: "status",
    sortable: true,
    type: "status",
  },
];

export const activeCampaignsData: ReportData[] = [
  {
    name: "Summer Promotion 2023",
    client: "Coca-Cola",
    startDate: "2023-06-01",
    endDate: "2023-08-31",
    budget: 75000,
    status: "Live",
  },
  {
    name: "Holiday Campaign",
    client: "Mercado Libre",
    startDate: "2023-11-15",
    endDate: "2023-12-31",
    budget: 120000,
    status: "Implementation",
  },
  {
    name: "Brand Awareness Q4",
    client: "Banorte",
    startDate: "2023-10-01",
    endDate: "2023-12-31",
    budget: 90000,
    status: "Live",
  },
  {
    name: "Product Launch",
    client: "Yakult",
    startDate: "2023-09-15",
    endDate: "2023-10-15",
    budget: 50000,
    status: "Closed",
  },
  {
    name: "Winter Special",
    client: "Warner Media",
    startDate: "2023-12-01",
    endDate: "2024-02-28",
    budget: 85000,
    status: "Pending",
  },
];

// Datos de ejemplo para el reporte de ingresos por organización
export const revenueByOrganizationData: ReportData[] = [
  {
    id: "1",
    organization: "Banorte",
    organizationType: "Agency",
    totalRevenue: 850000,
    grossMargin: 21.5,
    netRevenue: 182750,
    activeCampaigns: 3,
    completedCampaigns: 5,
    mainContact: "Alondra Vargas",
    billingCountry: "Mexico",
  },
  {
    id: "2",
    organization: "Coca-Cola",
    organizationType: "Direct",
    totalRevenue: 1250000,
    grossMargin: 25.0,
    netRevenue: 312500,
    activeCampaigns: 4,
    completedCampaigns: 8,
    mainContact: "John Smith",
    billingCountry: "United States",
  },
  {
    id: "3",
    organization: "Warner Media",
    organizationType: "Agency",
    totalRevenue: 750000,
    grossMargin: 20.0,
    netRevenue: 150000,
    activeCampaigns: 2,
    completedCampaigns: 3,
    mainContact: "Ana Rodriguez",
    billingCountry: "Argentina",
  },
  {
    id: "4",
    organization: "Mercado Libre",
    organizationType: "Direct",
    totalRevenue: 920000,
    grossMargin: 22.5,
    netRevenue: 207000,
    activeCampaigns: 3,
    completedCampaigns: 6,
    mainContact: "Carlos Lopez",
    billingCountry: "Mexico",
  },
  {
    id: "5",
    organization: "Penafiel",
    organizationType: "Agency",
    totalRevenue: 450000,
    grossMargin: 18.0,
    netRevenue: 81000,
    activeCampaigns: 2,
    completedCampaigns: 4,
    mainContact: "Maria Gonzalez",
    billingCountry: "Mexico",
  },
  {
    id: "6",
    organization: "Tramontina",
    organizationType: "Direct",
    totalRevenue: 380000,
    grossMargin: 19.5,
    netRevenue: 74100,
    activeCampaigns: 1,
    completedCampaigns: 2,
    mainContact: "Roberto Silva",
    billingCountry: "Brazil",
  },
  {
    id: "7",
    organization: "Yakult",
    organizationType: "Direct",
    totalRevenue: 520000,
    grossMargin: 23.0,
    netRevenue: 119600,
    activeCampaigns: 2,
    completedCampaigns: 3,
    mainContact: "Erika Negrete",
    billingCountry: "Mexico",
  },
];

// Datos de ejemplo para el reporte de performance de campañas
export const campaignPerformanceData: ReportData[] = [
  {
    id: "22043",
    name: "Banorte_Banorte_Hotsale _Credito Pyme _Linkedin_Mex_Junio25_Linkedin_Jun_Mexico",
    publisher: "Linkedin",
    impressions: 2500000,
    clicks: 75000,
    ctr: 3.0,
    viewability: 78.5,
    conversions: 3750,
    conversionRate: 5.0,
    cpc: 1.0,
    cpm: 30.0,
    spent: 75000,
    organization: "Banorte",
    trafficker: "Ana Sobreyra",
  },
  {
    id: "22044",
    name: "Coca-Cola_Summer_Campaign_2023",
    publisher: "YouTube",
    impressions: 4200000,
    clicks: 105000,
    ctr: 2.5,
    viewability: 82.3,
    conversions: 5250,
    conversionRate: 5.0,
    cpc: 0.95,
    cpm: 23.8,
    spent: 100000,
    organization: "Coca-Cola",
    trafficker: "Carlos Mendez",
  },
  {
    id: "22046",
    name: "Mercado Libre_MeliPlay_Fandom",
    publisher: "Fandom",
    impressions: 6500000,
    clicks: 195000,
    ctr: 3.0,
    viewability: 75.8,
    conversions: 9750,
    conversionRate: 5.0,
    cpc: 1.08,
    cpm: 32.3,
    spent: 210000,
    organization: "Mercado Libre",
    trafficker: "Maria Robles",
  },
  {
    id: "22047",
    name: "Penafiel_Coco Flavor_WeTransfer",
    publisher: "WeTransfer",
    impressions: 1800000,
    clicks: 54000,
    ctr: 3.0,
    viewability: 80.2,
    conversions: 2700,
    conversionRate: 5.0,
    cpc: 1.11,
    cpm: 33.3,
    spent: 60000,
    organization: "Penafiel",
    trafficker: "Luciana Egurrola",
  },
];

// Datos de ejemplo para el reporte de solicitudes HUR pendientes
export const pendingHURRequestsData: ReportData[] = [
  {
    id: "HUR-2025-001",
    requestNumber: "HUR-2025-001",
    requestDate: "2025-05-15",
    mediaType: "Online",
    publisher: "WeTransfer",
    campaign: "Yakult_Campaña anual_WeTransfer_Jun_Mexico",
    billingOffice: "Mexico City",
    status: "Pending",
    requestedBy: "Carlos Mendez",
    month: "06",
    year: "2025",
    currentAmount: 50000,
    newAmount: 55000,
    justification:
      "Ajuste de presupuesto debido a cambios en la estrategia de campaña.",
    daysInReview: 2,
  },
  {
    id: "HUR-2025-002",
    requestNumber: "HUR-2025-002",
    requestDate: "2025-05-16",
    mediaType: "Video",
    publisher: "YouTube",
    campaign: "Coca-Cola_Summer_Campaign_2025",
    billingOffice: "Miami",
    status: "In Review",
    requestedBy: "John Smith",
    assignedTo: "Maria Rodriguez",
    month: "07",
    year: "2025",
    currentAmount: 75000,
    newAmount: 72500,
    justification:
      "Reducción del presupuesto debido a menor rendimiento del esperado.",
    daysInReview: 1,
  },
  {
    id: "HUR-2025-003",
    requestNumber: "HUR-2025-003",
    requestDate: "2025-05-14",
    mediaType: "Social",
    publisher: "LinkedIn",
    campaign: "Banorte_Banorte_Hotsale _Credito Pyme _Linkedin_Mex_Junio25",
    billingOffice: "Mexico City",
    status: "Pending",
    requestedBy: "Ana Sobreyra",
    month: "06",
    year: "2025",
    currentAmount: 45000,
    newAmount: 60000,
    justification:
      "Incremento de presupuesto para ampliar alcance de la campaña.",
    daysInReview: 3,
  },
  {
    id: "HUR-2025-004",
    requestNumber: "HUR-2025-004",
    requestDate: "2025-05-10",
    mediaType: "Display",
    publisher: "Fandom",
    campaign: "Mercado Libre_MeliPlay_Fandom",
    billingOffice: "Mexico City",
    status: "In Review",
    requestedBy: "Octavio Martinez",
    assignedTo: "Gabriela Hurtado",
    month: "05",
    year: "2025",
    currentAmount: 65000,
    newAmount: 70000,
    justification: "Ajuste por ampliación del período de la campaña.",
    daysInReview: 7,
  },
];
