export interface AdOpsItem {
  id: string;
  month: string;
  salesPerson: string;
  driveLink: string;
  status: "Active" | "Paused" | "Completed" | "Draft";
  finalReport: boolean;
  notes: string;
  trafficker: string;
  advertiser: string;
  mmsId: string;
  mmsLine: string;
  boostrGamId: string;
  startDate: string;
  endDate: string;
  market: string;
  publisher: string;
  campaignType: string;
  purchaseType: string;
  platformCurrency: string;
  exchangeRate: number;
  campaign: string;
  format: string;
  productType: string;
  campaignName: string;
  usmcRate: number;
  publisherUnitCost: number;
  totalInvestmentUsd: number;
  totalInvestmentPublisherCurrency: number;
  contractedUnits: number;
  deliveredUnits: number;
  clicks: number;
  remainingUnits: number;
  estimatedDailyDelivery: number;
  effectiveDeliveryCost: number;
  dailySpend: number;
  deliveryPercentage: number;
  pacing: string;
  actualPlatformSpendLocalCurrency: number;
  remainingInvestment: number;
  actualPlatformSpendUsd: number;
  remainingInvestmentPercentage: number;
  consumedInvestmentPercentage: number;
  finalUnitCostPublisherCurrency: number;
  finalUnitCostUsd: number;
  ctr: number;
  vtr: number;
  viewabilityPercentage: number;
  boostrClosure: string;
  totalCampaignDays: number;
  totalElapsedDays: number;
  remainingDays: number;
  elapsedPercentage: number;
  product: string;
}

export const mockAdOpsData: AdOpsItem[] = [
  {
    id: "1",
    month: "June",
    salesPerson: "Juan Pérez",
    driveLink: "https://drive.google.com/file1",
    status: "Active",
    finalReport: false,
    notes: "Campaign in progress",
    trafficker: "Ana García",
    advertiser: "ABC Corporation",
    mmsId: "MMS-2023-001",
    mmsLine: "L1",
    boostrGamId: "B-12345",
    startDate: "2023-06-01",
    endDate: "2023-08-31",
    market: "Mexico",
    publisher: "Facebook",
    campaignType: "Branding",
    purchaseType: "CPM",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Summer 2023",
    format: "Display",
    productType: "PAS",
    campaignName: "Summer Promotion 2023",
    usmcRate: 5.5,
    publisherUnitCost: 4.2,
    totalInvestmentUsd: 50000,
    totalInvestmentPublisherCurrency: 50000,
    contractedUnits: 10000000,
    deliveredUnits: 6500000,
    clicks: 12500,
    remainingUnits: 3500000,
    estimatedDailyDelivery: 150000,
    effectiveDeliveryCost: 0.005,
    dailySpend: 1500,
    deliveryPercentage: 65,
    pacing: "On Track",
    actualPlatformSpendLocalCurrency: 32500,
    remainingInvestment: 17500,
    actualPlatformSpendUsd: 32500,
    remainingInvestmentPercentage: 35,
    consumedInvestmentPercentage: 65,
    finalUnitCostPublisherCurrency: 0.005,
    finalUnitCostUsd: 0.005,
    ctr: 0.19,
    vtr: 0,
    viewabilityPercentage: 70,
    boostrClosure: "2023-09-05",
    totalCampaignDays: 92,
    totalElapsedDays: 60,
    remainingDays: 32,
    elapsedPercentage: 65.2,
    product: "PAS",
  },
  {
    id: "2",
    month: "September",
    salesPerson: "María López",
    driveLink: "https://drive.google.com/file2",
    status: "Active",
    finalReport: false,
    notes: "Fall collection launch",
    trafficker: "Roberto Sánchez",
    advertiser: "Fashion Forward",
    mmsId: "MMS-2023-002",
    mmsLine: "L1",
    boostrGamId: "B-12346",
    startDate: "2023-09-01",
    endDate: "2023-10-31",
    market: "Colombia",
    publisher: "YouTube",
    campaignType: "Performance",
    purchaseType: "CPV",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Fall 2023",
    format: "Video",
    productType: "Fandom",
    campaignName: "Fall Collection Launch",
    usmcRate: 0.08,
    publisherUnitCost: 0.06,
    totalInvestmentUsd: 75000,
    totalInvestmentPublisherCurrency: 75000,
    contractedUnits: 1250000,
    deliveredUnits: 416667,
    clicks: 8400,
    remainingUnits: 833333,
    estimatedDailyDelivery: 20833,
    effectiveDeliveryCost: 0.06,
    dailySpend: 1250,
    deliveryPercentage: 33.33,
    pacing: "Behind",
    actualPlatformSpendLocalCurrency: 25000,
    remainingInvestment: 50000,
    actualPlatformSpendUsd: 25000,
    remainingInvestmentPercentage: 66.67,
    consumedInvestmentPercentage: 33.33,
    finalUnitCostPublisherCurrency: 0.06,
    finalUnitCostUsd: 0.06,
    ctr: 2.02,
    vtr: 75.5,
    viewabilityPercentage: 85,
    boostrClosure: "2023-11-05",
    totalCampaignDays: 61,
    totalElapsedDays: 20,
    remainingDays: 41,
    elapsedPercentage: 32.8,
    product: "Fandom",
  },
  {
    id: "3",
    month: "November",
    salesPerson: "Carlos Rodríguez",
    driveLink: "https://drive.google.com/file3",
    status: "Draft",
    finalReport: false,
    notes: "Pending approval",
    trafficker: "Pending assignment",
    advertiser: "Retail Giants",
    mmsId: "MMS-2023-003",
    mmsLine: "L1",
    boostrGamId: "B-12347",
    startDate: "2023-11-15",
    endDate: "2023-12-31",
    market: "Argentina",
    publisher: "Google Ads",
    campaignType: "Promotional",
    purchaseType: "CPM",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Christmas 2023",
    format: "Display",
    productType: "Sojern",
    campaignName: "Holiday Special",
    usmcRate: 4.8,
    publisherUnitCost: 3.5,
    totalInvestmentUsd: 100000,
    totalInvestmentPublisherCurrency: 100000,
    contractedUnits: 28571429,
    deliveredUnits: 0,
    clicks: 0,
    remainingUnits: 28571429,
    estimatedDailyDelivery: 612245,
    effectiveDeliveryCost: 0,
    dailySpend: 0,
    deliveryPercentage: 0,
    pacing: "Not Started",
    actualPlatformSpendLocalCurrency: 0,
    remainingInvestment: 100000,
    actualPlatformSpendUsd: 0,
    remainingInvestmentPercentage: 100,
    consumedInvestmentPercentage: 0,
    finalUnitCostPublisherCurrency: 0,
    finalUnitCostUsd: 0,
    ctr: 0,
    vtr: 0,
    viewabilityPercentage: 0,
    boostrClosure: "2024-01-05",
    totalCampaignDays: 47,
    totalElapsedDays: 0,
    remainingDays: 47,
    elapsedPercentage: 0,
    product: "Sojern",
  },
  {
    id: "4",
    month: "May",
    salesPerson: "Laura Martínez",
    driveLink: "https://drive.google.com/file4",
    status: "Completed",
    finalReport: true,
    notes: "Campaign successfully completed",
    trafficker: "Pedro Gómez",
    advertiser: "Startup Inc",
    mmsId: "MMS-2023-004",
    mmsLine: "L1",
    boostrGamId: "B-12348",
    startDate: "2023-05-01",
    endDate: "2023-07-31",
    market: "Chile",
    publisher: "Instagram",
    campaignType: "Awareness",
    purchaseType: "CPE",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "App Launch",
    format: "Social",
    productType: "WeTransfer",
    campaignName: "Brand Awareness",
    usmcRate: 0.15,
    publisherUnitCost: 0.12,
    totalInvestmentUsd: 30000,
    totalInvestmentPublisherCurrency: 30000,
    contractedUnits: 250000,
    deliveredUnits: 250000,
    clicks: 21000,
    remainingUnits: 0,
    estimatedDailyDelivery: 2717,
    effectiveDeliveryCost: 0.12,
    dailySpend: 326,
    deliveryPercentage: 100,
    pacing: "Completed",
    actualPlatformSpendLocalCurrency: 30000,
    remainingInvestment: 0,
    actualPlatformSpendUsd: 30000,
    remainingInvestmentPercentage: 0,
    consumedInvestmentPercentage: 100,
    finalUnitCostPublisherCurrency: 0.12,
    finalUnitCostUsd: 0.12,
    ctr: 8.4,
    vtr: 0,
    viewabilityPercentage: 92,
    boostrClosure: "2023-08-05",
    totalCampaignDays: 92,
    totalElapsedDays: 92,
    remainingDays: 0,
    elapsedPercentage: 100,
    product: "WeTransfer",
  },
  {
    id: "5",
    month: "October",
    salesPerson: "Diego Fernández",
    driveLink: "https://drive.google.com/file5",
    status: "Paused",
    finalReport: false,
    notes: "Paused due to budget review",
    trafficker: "Sofía Ramírez",
    advertiser: "Tech Innovations",
    mmsId: "MMS-2023-005",
    mmsLine: "L1",
    boostrGamId: "B-12349",
    startDate: "2023-10-01",
    endDate: "2023-12-15",
    market: "Peru",
    publisher: "TikTok",
    campaignType: "Engagement",
    purchaseType: "CPV",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "New Gadget",
    format: "CTV",
    productType: "Tinder",
    campaignName: "Product Launch",
    usmcRate: 0.09,
    publisherUnitCost: 0.07,
    totalInvestmentUsd: 45000,
    totalInvestmentPublisherCurrency: 45000,
    contractedUnits: 642857,
    deliveredUnits: 214286,
    clicks: 3200,
    remainingUnits: 428571,
    estimatedDailyDelivery: 0,
    effectiveDeliveryCost: 0.07,
    dailySpend: 0,
    deliveryPercentage: 33.33,
    pacing: "Paused",
    actualPlatformSpendLocalCurrency: 15000,
    remainingInvestment: 30000,
    actualPlatformSpendUsd: 15000,
    remainingInvestmentPercentage: 66.67,
    consumedInvestmentPercentage: 33.33,
    finalUnitCostPublisherCurrency: 0.07,
    finalUnitCostUsd: 0.07,
    ctr: 1.49,
    vtr: 82.1,
    viewabilityPercentage: 90.3,
    boostrClosure: "2023-12-20",
    totalCampaignDays: 76,
    totalElapsedDays: 25,
    remainingDays: 51,
    elapsedPercentage: 32.9,
    product: "Tinder",
  },
  {
    id: "6",
    month: "December",
    salesPerson: "Gabriela Torres",
    driveLink: "https://drive.google.com/file6",
    status: "Active",
    finalReport: false,
    notes: "Year-end campaign",
    trafficker: "Javier Morales",
    advertiser: "Retail Outlet",
    mmsId: "MMS-2023-006",
    mmsLine: "L1",
    boostrGamId: "B-12350",
    startDate: "2023-12-01",
    endDate: "2023-12-31",
    market: "Brazil",
    publisher: "Spotify",
    campaignType: "Promotional",
    purchaseType: "CPL",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Year End",
    format: "Audio",
    productType: "Vevo",
    campaignName: "Year-End Sale",
    usmcRate: 0.06,
    publisherUnitCost: 0.045,
    totalInvestmentUsd: 25000,
    totalInvestmentPublisherCurrency: 25000,
    contractedUnits: 555556,
    deliveredUnits: 111111,
    clicks: 1850,
    remainingUnits: 444445,
    estimatedDailyDelivery: 14815,
    effectiveDeliveryCost: 0.045,
    dailySpend: 667,
    deliveryPercentage: 20,
    pacing: "On Track",
    actualPlatformSpendLocalCurrency: 5000,
    remainingInvestment: 20000,
    actualPlatformSpendUsd: 5000,
    remainingInvestmentPercentage: 80,
    consumedInvestmentPercentage: 20,
    finalUnitCostPublisherCurrency: 0.045,
    finalUnitCostUsd: 0.045,
    ctr: 1.67,
    vtr: 0,
    viewabilityPercentage: 0,
    boostrClosure: "2024-01-10",
    totalCampaignDays: 31,
    totalElapsedDays: 6,
    remainingDays: 25,
    elapsedPercentage: 19.4,
    product: "Vevo",
  },
  {
    id: "7",
    month: "August",
    salesPerson: "Alejandro Mendoza",
    driveLink: "https://drive.google.com/file7",
    status: "Active",
    finalReport: false,
    notes: "Seasonal promotion",
    trafficker: "Isabel Vargas",
    advertiser: "Fashion Brand",
    mmsId: "MMS-2023-007",
    mmsLine: "L1",
    boostrGamId: "B-12351",
    startDate: "2023-08-15",
    endDate: "2023-10-15",
    market: "Colombia",
    publisher: "YouTube",
    campaignType: "Awareness",
    purchaseType: "CPV",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Spring 2023",
    format: "Video",
    productType: "Magnite",
    campaignName: "Spring Collection",
    usmcRate: 0.075,
    publisherUnitCost: 0.06,
    totalInvestmentUsd: 60000,
    totalInvestmentPublisherCurrency: 60000,
    contractedUnits: 1000000,
    deliveredUnits: 500000,
    clicks: 9500,
    remainingUnits: 500000,
    estimatedDailyDelivery: 8333,
    effectiveDeliveryCost: 0.06,
    dailySpend: 500,
    deliveryPercentage: 50,
    pacing: "On Track",
    actualPlatformSpendLocalCurrency: 30000,
    remainingInvestment: 30000,
    actualPlatformSpendUsd: 30000,
    remainingInvestmentPercentage: 50,
    consumedInvestmentPercentage: 50,
    finalUnitCostPublisherCurrency: 0.06,
    finalUnitCostUsd: 0.06,
    ctr: 1.9,
    vtr: 78.3,
    viewabilityPercentage: 82.5,
    boostrClosure: "2023-10-20",
    totalCampaignDays: 62,
    totalElapsedDays: 31,
    remainingDays: 31,
    elapsedPercentage: 50,
    product: "Magnite",
  },
  {
    id: "8",
    month: "July",
    salesPerson: "Ricardo Herrera",
    driveLink: "https://drive.google.com/file8",
    status: "Active",
    finalReport: false,
    notes: "Back to school campaign",
    trafficker: "Carmen Díaz",
    advertiser: "School Supplies Inc",
    mmsId: "MMS-2023-008",
    mmsLine: "L1",
    boostrGamId: "B-12352",
    startDate: "2023-07-15",
    endDate: "2023-09-15",
    market: "Mexico",
    publisher: "Facebook",
    campaignType: "Promotional",
    purchaseType: "CPM",
    platformCurrency: "USD",
    exchangeRate: 1,
    campaign: "Back to School",
    format: "Display",
    productType: "OneFootball",
    campaignName: "Back to School",
    usmcRate: 5.2,
    publisherUnitCost: 4.0,
    totalInvestmentUsd: 40000,
    totalInvestmentPublisherCurrency: 40000,
    contractedUnits: 10000000,
    deliveredUnits: 7500000,
    clicks: 15000,
    remainingUnits: 2500000,
    estimatedDailyDelivery: 41667,
    effectiveDeliveryCost: 0.004,
    dailySpend: 167,
    deliveryPercentage: 75,
    pacing: "Ahead",
    actualPlatformSpendLocalCurrency: 30000,
    remainingInvestment: 10000,
    actualPlatformSpendUsd: 30000,
    remainingInvestmentPercentage: 25,
    consumedInvestmentPercentage: 75,
    finalUnitCostPublisherCurrency: 0.004,
    finalUnitCostUsd: 0.004,
    ctr: 0.2,
    vtr: 0,
    viewabilityPercentage: 72.8,
    boostrClosure: "2023-09-20",
    totalCampaignDays: 63,
    totalElapsedDays: 47,
    remainingDays: 16,
    elapsedPercentage: 74.6,
    product: "OneFootball",
  },
];
