import {
  User,
  Role,
  Permission,
  UserRole,
  UserVisibility,
  ExchangeRate,
  InvoicingPeriod,
} from "@/types/users";

// Example data for users
export const mockUsers: User[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "+1234567890",
    country: "United States",
    username: "jsmith",
    isAdmin: true,
    noLimitAccess: true,
    active: true,
    role: "Admin, Executive",
    roles: ["Admin", "Executive"],
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-05-20T14:45:00Z",
  },
  {
    id: "2",
    firstName: "Maria",
    lastName: "Gonzalez",
    email: "maria.gonzalez@example.com",
    phone: "+0987654321",
    country: "Argentina",
    username: "mgonzalez",
    isAdmin: false,
    noLimitAccess: false,
    active: true,
    role: "Sales Manager, Account Manager",
    roles: ["Sales Manager", "Account Manager"],
    createdAt: "2023-02-10T09:15:00Z",
    updatedAt: "2023-05-18T11:20:00Z",
  },
  {
    id: "3",
    firstName: "Carlos",
    lastName: "Rodriguez",
    email: "carlos.rodriguez@example.com",
    phone: "+1122334455",
    country: "Colombia",
    username: "crodriguez",
    isAdmin: false,
    noLimitAccess: true,
    active: false,
    role: "Account Manager",
    roles: ["Account Manager"],
    createdAt: "2023-03-05T16:40:00Z",
    updatedAt: "2023-06-01T08:30:00Z",
  },
  {
    id: "4",
    firstName: "Ana",
    lastName: "Martinez",
    email: "ana.martinez@example.com",
    phone: "+5566778899",
    country: "Chile",
    username: "amartinez",
    isAdmin: false,
    noLimitAccess: false,
    active: true,
    role: "Traffic, Creative",
    roles: ["Traffic", "Creative"],
    createdAt: "2023-04-20T13:25:00Z",
    updatedAt: "2023-05-25T10:10:00Z",
  },
  {
    id: "5",
    firstName: "Robert",
    lastName: "Lopez",
    email: "robert.lopez@example.com",
    phone: "+1029384756",
    country: "Spain",
    username: "rlopez",
    isAdmin: false,
    noLimitAccess: false,
    active: true,
    role: "Accounting, Finance",
    roles: ["Accounting", "Finance"],
    createdAt: "2023-01-30T11:50:00Z",
    updatedAt: "2023-06-02T15:35:00Z",
  },
];

// Example data for permissions
export const mockPermissions: Permission[] = [
  {
    id: "p1",
    name: "view_campaigns",
    description: "View campaigns",
    module: "campaigns",
    action: "view",
  },
  {
    id: "p2",
    name: "create_campaigns",
    description: "Create campaigns",
    module: "campaigns",
    action: "create",
  },
  {
    id: "p3",
    name: "edit_campaigns",
    description: "Edit campaigns",
    module: "campaigns",
    action: "edit",
  },
  {
    id: "p4",
    name: "delete_campaigns",
    description: "Delete campaigns",
    module: "campaigns",
    action: "delete",
  },
  {
    id: "p5",
    name: "view_finance",
    description: "View finance",
    module: "finance",
    action: "view",
  },
  {
    id: "p6",
    name: "approve_finance",
    description: "Approve finance",
    module: "finance",
    action: "approve",
  },
  {
    id: "p7",
    name: "view_reports",
    description: "View reports",
    module: "reports",
    action: "view",
  },
  {
    id: "p8",
    name: "create_reports",
    description: "Create reports",
    module: "reports",
    action: "create",
  },
  {
    id: "p9",
    name: "view_users",
    description: "View users",
    module: "settings",
    action: "view",
  },
  {
    id: "p10",
    name: "edit_users",
    description: "Edit users",
    module: "settings",
    action: "edit",
  },
];

// Example data for roles
export const mockRoles: Role[] = [
  {
    id: "r1",
    name: "Administrator",
    description: "Full system access",
    module: "All",
    permissions: mockPermissions,
  },
  {
    id: "r2",
    name: "Sales",
    description: "Sales and campaign management",
    module: "Online",
    permissions: [
      mockPermissions[0],
      mockPermissions[1],
      mockPermissions[2],
      mockPermissions[6],
      mockPermissions[7],
    ],
  },
  {
    id: "r3",
    name: "Finance",
    description: "Financial management",
    module: "Offline",
    permissions: [
      mockPermissions[0],
      mockPermissions[4],
      mockPermissions[5],
      mockPermissions[6],
    ],
  },
  {
    id: "r4",
    name: "Traffic",
    description: "Traffic management",
    module: "OOH",
    permissions: [mockPermissions[0], mockPermissions[2], mockPermissions[6]],
  },
];

// Example data for user roles
export const mockUserRoles: UserRole[] = [
  { userId: "1", roleId: "r1", role: mockRoles[0] },
  { userId: "2", roleId: "r2", role: mockRoles[1] },
  { userId: "3", roleId: "r3", role: mockRoles[2] },
  { userId: "4", roleId: "r4", role: mockRoles[3] },
  { userId: "5", roleId: "r2", role: mockRoles[1] },
];

// Example data for user visibility
export const mockUserVisibility: UserVisibility[] = [
  { userId: "1", visibleUserId: "2", visibleUser: mockUsers[1] },
  { userId: "1", visibleUserId: "3", visibleUser: mockUsers[2] },
  { userId: "1", visibleUserId: "4", visibleUser: mockUsers[3] },
  { userId: "1", visibleUserId: "5", visibleUser: mockUsers[4] },
  { userId: "2", visibleUserId: "4", visibleUser: mockUsers[3] },
  { userId: "2", visibleUserId: "5", visibleUser: mockUsers[4] },
  { userId: "3", visibleUserId: "5", visibleUser: mockUsers[4] },
];

// Example data for exchange rates
export const mockExchangeRates: ExchangeRate[] = [
  {
    id: "e1",
    fromCurrency: "USD",
    toCurrency: "MXN",
    rate: 17.25,
    date: "2023-06-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2023-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e2",
    fromCurrency: "USD",
    toCurrency: "ARS",
    rate: 350.75,
    date: "2023-06-01",
    updatedBy: "jsmith",
    status: "active",
    createdAt: "2023-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e3",
    fromCurrency: "USD",
    toCurrency: "COP",
    rate: 4150.3,
    date: "2023-06-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2023-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e4",
    fromCurrency: "USD",
    toCurrency: "EUR",
    rate: 0.92,
    date: "2023-06-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2023-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e5",
    fromCurrency: "USD",
    toCurrency: "BRL",
    rate: 4.95,
    date: "2023-06-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2023-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  // Additional mock history to visualize versions per currency
  {
    id: "e6",
    fromCurrency: "USD",
    toCurrency: "MXN",
    rate: 16.9,
    date: "2024-12-15",
    updatedBy: "mgonzalez",
    status: "active",
    createdAt: "2024-12-15T10:00:00Z",
    createdBy: "mgonzalez",
  },
  {
    id: "e7",
    fromCurrency: "USD",
    toCurrency: "MXN",
    rate: 17.6,
    date: "2024-03-10",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2024-03-10T09:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e8",
    fromCurrency: "USD",
    toCurrency: "COP",
    rate: 4015.8,
    date: "2024-11-01",
    updatedBy: "amartinez",
    status: "active",
    createdAt: "2024-11-01T11:30:00Z",
    createdBy: "amartinez",
  },
  {
    id: "e9",
    fromCurrency: "USD",
    toCurrency: "EUR",
    rate: 0.94,
    date: "2025-02-01",
    updatedBy: "rlopez",
    status: "active",
    createdAt: "2025-02-01T08:00:00Z",
    createdBy: "rlopez",
  },
  {
    id: "e10",
    fromCurrency: "USD",
    toCurrency: "EUR",
    rate: 0.9,
    date: "2024-06-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2024-06-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e11",
    fromCurrency: "USD",
    toCurrency: "BRL",
    rate: 5.1,
    date: "2025-01-05",
    updatedBy: "mgonzalez",
    status: "active",
    createdAt: "2025-01-05T12:00:00Z",
    createdBy: "mgonzalez",
  },
  {
    id: "e12",
    fromCurrency: "USD",
    toCurrency: "ARS",
    rate: 330.0,
    date: "2023-03-01",
    updatedBy: "jsmith",
    status: "inactive",
    createdAt: "2023-03-01T00:00:00Z",
    createdBy: "jsmith",
  },
  {
    id: "e13",
    fromCurrency: "USD",
    toCurrency: "CLP",
    rate: 920.5,
    date: "2025-01-20",
    updatedBy: "amartinez",
    status: "active",
    createdAt: "2025-01-20T09:45:00Z",
    createdBy: "amartinez",
  },
  {
    id: "e14",
    fromCurrency: "USD",
    toCurrency: "CLP",
    rate: 950.0,
    date: "2024-08-10",
    updatedBy: "amartinez",
    status: "inactive",
    createdAt: "2024-08-10T09:45:00Z",
    createdBy: "amartinez",
  },
  {
    id: "e15",
    fromCurrency: "USD",
    toCurrency: "PEN",
    rate: 3.85,
    date: "2025-02-10",
    updatedBy: "crodriguez",
    status: "active",
    createdAt: "2025-02-10T14:10:00Z",
    createdBy: "crodriguez",
  },
  {
    id: "e16",
    fromCurrency: "USD",
    toCurrency: "PEN",
    rate: 3.78,
    date: "2024-09-12",
    updatedBy: "crodriguez",
    status: "inactive",
    createdAt: "2024-09-12T14:10:00Z",
    createdBy: "crodriguez",
  },
  {
    id: "e17",
    fromCurrency: "USD",
    toCurrency: "GBP",
    rate: 0.79,
    date: "2025-02-18",
    updatedBy: "rlopez",
    status: "active",
    createdAt: "2025-02-18T10:20:00Z",
    createdBy: "rlopez",
  },
  {
    id: "e18",
    fromCurrency: "USD",
    toCurrency: "GBP",
    rate: 0.78,
    date: "2024-10-18",
    updatedBy: "rlopez",
    status: "inactive",
    createdAt: "2024-10-18T10:20:00Z",
    createdBy: "rlopez",
  },
];

// Example data for invoicing periods
export const mockInvoicingPeriods: InvoicingPeriod[] = [
  {
    id: "i1",
    name: "Q1 2023",
    startDate: "2023-01-01",
    endDate: "2023-03-31",
    status: "closed",
    module: "Online",
    createdAt: "2022-12-15T10:00:00Z",
    updatedAt: "2023-04-05T14:30:00Z",
  },
  {
    id: "i2",
    name: "Q2 2023",
    startDate: "2023-04-01",
    endDate: "2023-06-30",
    status: "closed",
    module: "OOH",
    createdAt: "2023-03-15T11:00:00Z",
    updatedAt: "2023-07-05T09:45:00Z",
  },
  {
    id: "i3",
    name: "Q3 2023",
    startDate: "2023-07-01",
    endDate: "2023-09-30",
    status: "processing",
    module: "Broadcast",
    createdAt: "2023-06-15T08:30:00Z",
    updatedAt: "2023-10-02T16:20:00Z",
  },
  {
    id: "i4",
    name: "Q4 2023",
    startDate: "2023-10-01",
    endDate: "2023-12-31",
    status: "open",
    module: "Print",
    createdAt: "2023-09-15T13:45:00Z",
    updatedAt: "2023-09-15T13:45:00Z",
  },
  {
    id: "i5",
    name: "January 2024",
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    status: "open",
    module: "Online",
    createdAt: "2023-12-15T10:30:00Z",
    updatedAt: "2023-12-15T10:30:00Z",
  },
];
